default: &default
  adapter: postgresql
  encoding: unicode
  pool: 12
  template: template0

development:
  <<: *default
  database: govuk-content-block-manager_development
  url: <%= ENV["DATABASE_URL"]%>

test:
  <<: *default
  database: govuk-content-block-manager_test
  url: <%= ENV["TEST_DATABASE_URL"] %>

production:
  <<: *default
  database: govuk-content-block-manager_production
  url: <%= ENV["DATABASE_URL"]%>
